export const POTENTIAL_PARTNERS = [
  { name: 'Carmangeria Ozana', type: 'carmangerie', website: 'https://carmangeriaozana.ro', city: 'București' },
  { name: 'Carmangeria Dumi', type: 'carmangerie', website: 'https://www.carmangeriadumi.ro', city: 'București' },
  { name: 'Carmangeria Godac', type: 'carmangerie', website: 'https://www.carmangeriagodac.ro', city: 'București' },
  { name: 'Karmangeria', type: 'carmangerie', website: 'https://www.karmangeria.ro', city: 'București' },
  { name: 'La Mircea Măcelaru', type: 'carmangerie', website: 'https://lamirceamacelaru.ro', city: 'București' },
  { name: 'Măcelărie Turcească', type: 'carmangerie', website: 'https://www.macelarieturceasca.ro', city: 'București' },
  { name: 'H&G Carmangerie', type: 'carmangerie', website: 'https://hgcarmangerie.metro.rest', city: 'București' },
  { name: 'Casa Angus', type: 'carmangerie', website: 'https://www.casa-angus.ro', city: 'București' },
  { name: 'Carmangeria Moldovan', type: 'carmangerie', website: 'https://www.carmangeriamoldovan.ro', city: 'București' },
  { name: 'La Cătălin', type: 'mixt', website: 'https://la-catalin.ro', city: 'București' },
  { name: 'Carmangeria Titulescu', type: 'carmangerie', website: 'https://carmangeriatitulescu.ro', city: 'București' },
  { name: 'Coana Chirița', type: 'mixt', website: 'http://www.coanachirita.ro', city: 'București' },
  { name: 'Băcănia Gramador', type: 'mixt', website: 'https://bacaniagramador.ro', city: 'București' },
  { name: 'Băcănia Boierească', type: 'mixt', website: 'https://www.bucuresti.bacaniaboiereasca.ro', city: 'București' },
  { name: 'Băcănia Veche', type: 'mixt', website: 'https://bacaniaveche.ro', city: 'București' },
  { name: 'Băcănia Fermierului', type: 'mixt', website: 'https://bacaniafermierului.ro', city: 'București' },
  { name: 'Băcănia Rod', type: 'mixt', website: 'https://www.bacaniarod.ro', city: 'București' },
  { name: 'Băcănia La Stan', type: 'mixt', website: 'https://bacanialastan.ro', city: 'București' },
  { name: 'La Baciu', type: 'mixt', website: 'http://www.labaciu.ro', city: 'București' },
  { name: 'Real Foods', type: 'mixt', website: 'https://realfoods.ro', city: 'București' },
  { name: 'Pukka Food', type: 'mixt', website: 'https://www.pukkafood.ro', city: 'București' },
  { name: 'Lăptăria cu Caimac', type: 'lactate', website: 'https://laptariacucaimac.ro', city: 'București' },
  { name: 'Napolact', type: 'lactate', website: 'https://www.napolact.ro', city: 'București' },
  { name: 'Covalact', type: 'lactate', website: 'https://www.covalact.ro', city: 'București' },
  { name: 'Olympus', type: 'lactate', website: 'https://www.olympusdairy.ro', city: 'București' },
  { name: 'Delaco', type: 'lactate', website: 'https://www.delaco.ro', city: 'București' },
  { name: 'Hochland', type: 'lactate', website: 'https://www.hochland.ro', city: 'București' },
  { name: 'Mega Image', type: 'mixt', website: 'https://www.mega-image.ro', city: 'București' },
  { name: 'Carrefour', type: 'mixt', website: 'https://www.carrefour.ro', city: 'București' },
  { name: 'Auchan', type: 'mixt', website: 'https://www.auchan.ro', city: 'București' },
  { name: 'Selgros', type: 'mixt', website: 'https://www.selgros.ro', city: 'București' },
  { name: 'Metro', type: 'mixt', website: 'https://www.metro.ro', city: 'București' },
  { name: 'Kaufland', type: 'mixt', website: 'https://www.kaufland.ro', city: 'București' },
  { name: 'Profi', type: 'mixt', website: 'https://www.profi.ro', city: 'București' },
  { name: 'Lidl', type: 'mixt', website: 'https://www.lidl.ro', city: 'București' },
  { name: 'Penny', type: 'mixt', website: 'https://www.penny.ro', city: 'București' },
  { name: 'LaDoiPași', type: 'mixt', website: 'https://www.ladoipasi.ro', city: 'București' },
  { name: 'Froopt', type: 'mixt', website: 'https://www.froopt.ro', city: 'București' },
  { name: 'SuperMercato', type: 'mixt', website: 'https://www.supermercato.ro', city: 'București' },
  { name: 'Sezamo', type: 'mixt', website: 'https://www.sezamo.ro', city: 'București' },
  { name: 'Freshful', type: 'mixt', website: 'https://www.freshful.ro', city: 'București' },
  { name: 'Bringo', type: 'mixt', website: 'https://www.bringo.ro', city: 'București' },
  { name: 'Gusturi Românești', type: 'mixt', website: 'https://www.gusturi-romanesti.ro', city: 'București' },
  { name: 'Ferma Baciu', type: 'carmangerie', website: 'https://www.ferma-baciu.ro', city: 'București' },
  { name: 'Ferma noastră', type: 'lactate', website: 'https://www.fermanoastra.ro', city: 'București' },
  { name: 'Lactate Brădet', type: 'lactate', website: 'https://www.bradetlactate.ro', city: 'București' },
  { name: 'Simultan', type: 'lactate', website: 'https://www.simultan.ro', city: 'București' },
  { name: 'Five Continents', type: 'lactate', website: 'https://www.fivecontinents.ro', city: 'București' },
  { name: 'Ana și Cornel', type: 'carmangerie', website: 'https://www.anasicornel.ro', city: 'București' },
  { name: 'Aldis', type: 'carmangerie', website: 'https://www.aldis.ro', city: 'București' },
  { name: 'Cris-Tim', type: 'carmangerie', website: 'https://www.cristim.ro', city: 'București' },
  { name: 'Caroli', type: 'carmangerie', website: 'https://www.caroli.ro', city: 'București' },
  { name: 'Reinert', type: 'carmangerie', website: 'https://www.reinert.ro', city: 'București' },
  { name: 'Elit', type: 'carmangerie', website: 'https://www.elit.ro', city: 'București' },
  { name: 'Angst', type: 'carmangerie', website: 'https://www.angst.ro', city: 'București' },
  { name: 'Kosarom', type: 'carmangerie', website: 'https://www.kosarom.ro', city: 'București' },
  { name: 'Meda', type: 'carmangerie', website: 'https://www.meda.ro', city: 'București' },
  { name: 'Fox', type: 'carmangerie', website: 'https://www.fox.ro', city: 'București' },
  { name: 'Sergiana', type: 'carmangerie', website: 'https://www.sergiana.ro', city: 'București' },
  { name: 'Marcel', type: 'carmangerie', website: 'https://www.marcelprod.ro', city: 'București' },
  { name: 'Doly-Com', type: 'carmangerie', website: 'https://www.doly-com.ro', city: 'București' },
  { name: 'Agricola', type: 'carmangerie', website: 'https://www.agricola.ro', city: 'București' },
  { name: 'Transavia', type: 'carmangerie', website: 'https://www.transavia.ro', city: 'București' },
  { name: 'Delicii Libaneze', type: 'mixt', website: 'https://www.deliciilibaneze.ro', city: 'București' },
  { name: 'Cofetăria Alice', type: 'mixt', website: 'https://cofetariaalice.ro', city: 'București' },
  { name: 'Boutique du Pain', type: 'mixt', website: 'https://boutiquedupain.ro', city: 'București' },
  { name: 'Grano', type: 'mixt', website: 'https://www.grano.ro', city: 'București' },
  { name: 'Mega Delicatese', type: 'mixt', website: 'https://megadelicatese.ro', city: 'București' },
  { name: 'FineStore', type: 'mixt', website: 'https://www.finestore.ro', city: 'București' },
];
